services:
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: spectralvpn-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    extra_hosts:
      - host.docker.internal:172.17.0.1
    ports:
      - 8000:8000
    
  #web:
    # Todo
  db:
    image: postgres:latest
    container_name: spectralvpn-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql
    #TODO Удалить проброс портов
    ports:
      - 5432:5432

volumes:
  db-data:
